### ISSUE TITLE
rtm

### ISSUE THREAD

**Issue by flower-pot** [julienXX/clj-slack#18]
I want to create a slack bot that listens to specific words in a channel and answers to those. From my understanding, I need to use the real-time-messaging API from slack. My problem is, other than creating a session I don't understand how to use it from the docs or the code.

**Comment by casidiablo** [comment]
For that we wrote this one: https://github.com/casidiablo/slack-rtm

It uses `clj-slack` but provides an API to integrate with RTM based on `core.async`.

**Comment by flower-pot** [comment]
Thanks for the quick response! I'll give it a try! :+1:
