### ISSUE TITLE
Trying to send String's containing whitespace raises StringReader exception

### ISSUE THREAD

**Issue by juszczakn** [julienXX/clj-slack#3]
Since everything is sent through URL params, trying to send String's containing spaces raises an not-so-related StringReader NullPointerException.  This means to send strings, users need to UrlEncode them before sending. 

I believe this should be handled by the library or mentioned in the doc(string)s.

**Comment by julienXX** [comment]
Good point thanks! You're right the lib should handle this.

**Comment by julienXX** [comment]
@juszczakn can you show me how you made the lib fail? I can't reproduce it. Did you put your access token in .lein-env at the root of your project?

**Comment by juszczakn** [comment]
(clj-slack.channels/post-message channel-id "hi hello")

NullPointerException   java.io.StringReader.<init> (StringReader.java:50)

    1. Unhandled java.lang.NullPointerException
       (No message)

             StringReader.java:   50  java.io.StringReader/<init>
                      json.clj:  278  clojure.data.json/read-str
                   RestFn.java:  410  clojure.lang.RestFn/invoke
                      core.clj:   13  clj-slack.core/send-request
                      core.clj:   30  clj-slack.core/slack-request
                      chat.clj:   12  clj-slack.chat/post-message
                          REPL:    1  run-db-script-qa.slack/eval5220
                 Compiler.java: 6703  clojure.lang.Compiler/eval
                 Compiler.java: 6666  clojure.lang.Compiler/eval
                      core.clj: 2927  clojure.core/eval
                      main.clj:  239  clojure.main/repl/read-eval-print/fn
                      main.clj:  239  clojure.main/repl/read-eval-print
                      main.clj:  257  clojure.main/repl/fn
                      main.clj:  257  clojure.main/repl
                   RestFn.java: 1523  clojure.lang.RestFn/invoke
        interruptible_eval.clj:   67  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
                      AFn.java:  152  clojure.lang.AFn/applyToHelper
                      AFn.java:  144  clojure.lang.AFn/applyTo
                      core.clj:  624  clojure.core/apply
                      core.clj: 1862  clojure.core/with-bindings*
                   RestFn.java:  425  clojure.lang.RestFn/invoke
        interruptible_eval.clj:   51  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
        interruptible_eval.clj:  183  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
        interruptible_eval.clj:  152  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
                      AFn.java:   22  clojure.lang.AFn/run
         ThreadPoolExecutor.java: 1146  java.util.concurrent.ThreadPoolExecutor/runWorker
         ThreadPoolExecutor.java:  615  java.util.concurrent.ThreadPoolExecutor$Worker/run
                   Thread.java:  701  java.lang.Thread/run

**Comment by julienXX** [comment]
hmm post-message is in cli-slack.chat namespace but I guess it's a typo. Nevertheless I can't reproduce it :/

**Comment by juszczakn** [comment]
I updated the comment with exact steps to reproduce. 

project.clj dependencies:
                [[org.clojure/clojure "1.6.0"]
                 [org.clojure/java.jdbc "0.3.6"]
                 ;[net.sourceforge.jtds/jtds "1.2.4"]
                 [com.microsoft/sqljdbc4 "3.0"]
                 [org.clojure/tools.cli "0.3.1"]
                 [org.julienxx/clj-slack "0.1.1"]]

**Comment by julienXX** [comment]
Really weird, here's what I get:
```
λ lein repl
nREPL server started on port 53023 on host 127.0.0.1
REPL-y 0.3.0
Clojure 1.6.0
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (require 'clj-slack.channels)
nil
user=> (require 'clj-slack.chat)
nil
user=> (def channel-id (first (map #(get % "id") (get (clj-slack.channels/list) "channels"))))
#'user/channel-id
user=> (clj-slack.chat/post-message channel-id "hi hello")
{"ok" true, "channel" "C03BRD2XX", "ts" "1422027366.000006"}
```

**Comment by julienXX** [comment]
@juszczakn I tried reproducing with a new app and it's working. 
I can get the same error you have when my .lein-env is empty. 
If you print channel-id in your steps above, do you get something?

**Comment by juszczakn** [comment]
Yes, there is a valid slack-token in .lein-env. 

This is how I currently get around it:

    test.core=> (import '[java.net URLEncoder])
    java.net.URLEncoder
    test.core=> (clj-slack.chat/post-message channel-id (URLEncoder/encode "hi hello"))
    {"ok" true, "channel" "C02N34ULA", "ts" "1422321947.000343"}
    test.core=>
