### ISSUE TITLE
CompilerException java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by micrub** [julienXX/clj-slack#34]
While using `[org.julienxx/clj-slack "0.5.2.1"]` getting following compilation error:
```
(require 'clj-slack.users)

CompilerException java.lang.IllegalArgumentException: Can't define method not in interfaces: meta, compiling:(clj_http/headers.clj:105:1)
```

**Comment by micrub** [comment]
FYK.

Switching from `[prismatic/schema "0.1.1"]` to `[prismatic/schema "1.0.4"]` solved the compilation error.

**Comment by julienXX** [comment]
Great thanks for the insight.
