### ISSUE TITLE
missing_scope

### ISSUE THREAD

**Issue by kwladyka** [julienXX/clj-slack#41]
Whatever i am trying to do i get an error:
```clojure
(channels/list connection)
{:ok false, :error "missing_scope", :needed "channels:read", :provided "identify,incoming-webhook"}
```

**Comment by julienXX** [comment]
Thanks! Can't reproduce the issue with my token, I'll check with another one.

**Comment by kwladyka** [comment]
Hmm i am getting the token from the app settings like on the screen.

<img width="1157" alt="screen shot 2017-03-02 at 22 19 13" src="https://cloud.githubusercontent.com/assets/3903726/23527482/688707bc-ff96-11e6-8ae1-45f1a566905c.png">

**Comment by julienXX** [comment]
The app creation flow changed quite a bit it seems, I need to check it out and update the documentation accordingly.
When creating a new app, there's a permissions step where you can choose some more permissions it seems. That might solve your issue.

**Comment by kwladyka** [comment]
Thank you. It works but adding scopes slack UI doesn't work so well. Maybe only on Safari, i didn't try other web browser. The list of promts doesn't show. I achieved this by write "chat" and push two times arrow down. Totally good luck.
