### ISSUE TITLE
[bug?] always post-message as a owner of the app

### ISSUE THREAD

**Issue by kwladyka** [julienXX/clj-slack#42]
```clojure
(chat/post-message connection "#logs" "" {
                                            :attachments [{"text" text
                                                           "color" color}]})
```

Posted as a user who created the app?!

```clojure
(chat/post-message connection "#logs" "" {:username "Overseer"
                                            :attachments [{"text" text
                                                           "color" color}]})
```

The same.

```clojure
(chat/post-message connection "#logs" "" {
                                            :as_username false/true
                                            :attachments [{"text" text
                                                           "color" color}]})
```

`CompilerException java.lang.IllegalArgumentException: Body may not be null, compiling:(.../src/.../slack.clj:27:1) `

```clojure
(chat/post-message connection "#logs" "" {:as_username "Overseer"
                                            :attachments [{"text" text
                                                           "color" color}]})
```

No errors but posted as a user who created the app.

The goal: i want to post messages as a bot / another user. Whatever but not me :)

**Comment by kwladyka** [comment]
Ah sorry again. It is about scopes again... I had to add `chat:write:bot`. Anyway it is confused API posted messages as me...

But the bug with `:as_username` when true/false is probably just a bug :)

**Comment by julienXX** [comment]
No worries :) Scopes weren't really there when I last updated clj-slack, I'll have to update some stuff. Thanks for reporting issues!

**Comment by julienXX** [comment]
@kwladyka the correct param is "as_user" not "as_username" and the value should be a string, at least this worked for me:
`(clj-slack.chat/post-message connection "#logs" "test" {:as_user "true"})`
