### ISSUE TITLE
No configuration for timeouts.

### ISSUE THREAD

**Issue by jumarko** [julienXX/clj-slack#48]
I couldn't find anything related to timeouts and I think this is a huge opportunity for improvement.
It should be possible (and really encouraged) to specify reasonable timeouts for every slack operation.
Otherwise, the app can freeze indefinitely.

clj-http provides a couple of options for configuring timeouts: https://github.com/dakrone/clj-http#post

* `:conn-timeout`
* `:socket-timeout`

There's also `:conn-request-timeout` but I guess that's not that important since it's a timeout for requesting a connection from connection manager.

There could a default (e.g. 60 seconds) for both timeouts too.

**Comment by julienXX** [comment]
@jumarko that's a great idea thanks! Would you like to submit a PR for this option?

**Comment by jumarko** [comment]
Here's one possible solution. I haven't done extensive testing but tried this with very short timeouts and also with longer timeouts behind a firewall. In those scenarios it seems to work properly.
Note: I tested it using only `chat/post-message`. However, it seems that all high-level APIs use either `send-request` or `send-post-request` so it should be applicable everywhere.

**Comment by julienXX** [comment]
Thanks a lot! This looks very good, I’ll do some testing tomorrow and issue a new release if everything looks fine 👍

**Comment by jumarko** [comment]
Tests are failing (see Travis build link in PR) but they seem to fail on the master branch too.
