### ISSUE TITLE
Supply Client ID and Client Secret using Basic auth

### ISSUE THREAD

**Issue by danielcompton** [julienXX/clj-slack#50]
On the [oauth.access](https://api.slack.com/methods/oauth.access) method, the docs say:

> We strongly recommend supplying the Client ID and Client Secret using the HTTP Basic authentication scheme, as discussed in [RFC 6749](https://tools.ietf.org/html/rfc6749#section-2.3.1).

It could be good to do this instead of providing them in the URL parameters, I think?

https://github.com/julienXX/clj-slack/blob/446bba83899d4a16299ea2764cbd114852da299b/src/clj_slack/oauth.clj#L10-L11

**Comment by julienXX** [comment]
Hi @danielcompton thanks for opening this issue. Would you be interested in opening a pull request to change this?
