### ISSUE TITLE
can't load clj-slack.users

### ISSUE THREAD

**Issue by martinklepsch** [julienXX/clj-slack#53]
Seems like `stringily-keys` is missing: https://github.com/julienXX/clj-slack/blob/893440323a1038bcf2e9a2882cf0adb26515ac99/src/clj_slack/users.clj#L18

PS: I found this issue because the [cljdoc](https://cljdoc.org) documentation build for clj-slack failed (see [build](https://cljdoc.org/builds/6818)).

**Comment by julienXX** [comment]
Oh good catch thanks! I’ll fix it ASAP

**Comment by julienXX** [comment]
Released 0.6.2. Let me know if you encounter any issues. Thanks again!

**Comment by martinklepsch** [comment]
Looks good! https://cljdoc.org/d/org.julienxx/clj-slack/0.6.2
