### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by casidiablo** [julienXX/clj-slack#9]
It seems like that's what is next in your plate... let me know if you plan to start doing it anytime soon or if I should take a stab at it.

CI and testing against our own slack team would be great. What do you think? I already have one team setup for this project and it's the one I'm using to manually test the library.

**Comment by julienXX** [comment]
Yeah that's a nice idea to add our own slack team to test the lib. I'll attack it soon. Can you add me to the slack (email on my profile)? We can then discuss this further up.
What I had in mind is using property based tests for the endpoints and regular unit tests for core.clj.

**Comment by casidiablo** [comment]
Cool... I think the simplest CI we can start with is travis-ci.org

I will PR a basic setup for travis. Could you please enable CI for this project in travis?
